version: "3"
services:
  spark-master:
    image: "dasilva_master:latest"
    ports:
      - "8080:8080"
      - "7077:7077"
      - "8888:8888"
    networks:
      - spark-net
    deploy:
      placement:
        # set node labels using docker node update --label-add key=value <NODE ID> from swarm manager
        constraints:
          - node.labels.role==master
  spark-worker:
    image: "sdesilva26/spark_worker:0.0.2"
    ports:
      - "8081:8081"
    environment:
      - CORES=2
      - MEMORY=2G
    deploy:
      placement:
        # set node labels using docker node update --label-add key=value <NODE ID> from swarm manager
        constraints:
          - node.labels.role==worker
      replicas: 3
    networks:
      - spark-net
networks:
  spark-net:
    driver: overlay
